### PR TITLE
Fixed json with all sha-1 and fixed sonar in app build.gradle

### PR DESCRIPTION
**Pull request by CassioManuguerra**

### CODE REVIEW

**Comment by Andy130604** [comment]
GGWP

**Review by Andy130604 — APPROVED** [review]
LGTM

**Comment by CassioManuguerra** [comment]
ty bros it means a lot ^_^

**Comment by zouyonghao** [comment]
Good patch! Also, try to fix the code format before merging.

**Comment by CassioManuguerra** [comment]
> Good patch! Also, try to fix the code format before merging.

You are right this was a mistake due to the fact that we had not yet enforced a rule to prevent pushing without a passing CI and it will not happen again

**Pull request merged**
