### PR TITLE
androidtests on login screen

### PR DESCRIPTION
**Pull request by ecornamu**
Performed Android testing on the reachable parts of the `LoginScreen` and `LoginContent` composables.

### CODE REVIEW

**Comment by JoniDutoit** [comment]
Great job testing the login screen, LGTM !

**Comment by JoniDutoit** [comment]
Great job testing the login screen, LGTM !

**Review by JoniDutoit — APPROVED** [review]
Great job testing the login screen, LGTM !

**Review by JeremyHugentobler — APPROVED** [review]
Thank you for the tests

**Pull request merged**
