### PR TITLE
HelperFunctionTest 

### PR DESCRIPTION
**Pull request by npfrei**
Tests of the HelperFunctions class, has 100% jacoco line coverage 
image

### CODE REVIEW

**Review by CassioManuguerra — APPROVED** [review]
psheesh, solid testing skills from the scrum king, as expected.
If I could allow myself one suggestion, it would be to maybe comment a bit the tests, even if they are very straight-forward.
Else from that LGTM.

**Review by JeremyHugentobler — APPROVED** [review]
Unmatched tester, an inspiration.

Thank you for your work and hopefully good night !

**Review by Andy130604 — APPROVED** [review]
Is this the ScrumKing or what? You are a beast Keep up the insane work

**Comment by Thimphou** [comment]
GOAT of testing, great work from our beloved SM.

**Pull request merged**
